PVP=true
PVPLogToolChat=true
PVPLogToolFile=true
PauseEmpty=true
GlobalChat=true
ChatStreams=s,r,a,w,y,sh,f,all
Open=true
ServerWelcomeMessage=Welcome to Project Zomboid B42 Modded Server!
DisplayUserName=true
ShowFirstAndLastName=false
SpawnPoint=0,0,0
SafetySystem=true
ShowSafety=true
SafetyToggleTimer=2
SafetyCooldownTimer=3
SafetyDisconnectDelay=60
SpawnItems=
DefaultPort=16261
UDPPort=16262
ResetID=123456789

# Моды (коллекция 3781238575)
Mods=PROJECTRVInterior42;NeatUIFramework;TsarsCommonLibraryB42;errorMagnifier;ChuckleberryFinnAlertSystem;BetterSorting;StandardizedVehicleUpgrades3Core;StandardizedVehicleUpgrades3V;RVInteriorExpansion;RVInteriorExpansionPart2;Project_Cook;Neat_Crafting;BanditsNPC;WanderingZombies;WanderingZombiesRU;ObviousSkillTapes;TheBestLockpicking;JumboTreeIndoorFix;CyesPushDoors

# Карты (map_distanciado первая для RV!)
Map=map_distanciado;Muldraugh, KY;West Point, KY;Rosewood, KY;Riverside, KY;March Ridge, KY;Louisville, KY;Valley Station, KY

# ID модов
WorkshopItems=3543229299;3508537032;3402491515;2896041179;3077900375;2313387159;3403490889;3304582091;3618427553;3622163276;3490188370;3502080466;3268487204;2983905789;3708476455;3739168410;3745815281;3774826484;3780683663

# Безопасность и античит (ВСЁ ВЫКЛЮЧЕНО)
DoLuaChecksum=false
SteamVAC=false
AntiCheatSafety=0
AntiCheatMovement=0
AntiCheatHit=0
AntiCheatPacket=0
AntiCheatPermission=0
AntiCheatXP=0
AntiCheatSafeHouse=0
AntiCheatPlayer=0
AntiCheatChecksum=0
AntiCheatItem=0

SaveWorldEveryMinutes=15

Public=true
PublicName=My PZ B42 Modded Server
PublicDescription=RV Interior, Bandits NPC, Wandering Zombies, Lockpicking, Better Sorting
MaxPlayers=32
PingLimit=0

Password=667
RCONPort=27015
RCONPassword=YourStrongPasswordHere

PlayerSafehouse=false
AdminSafehouse=false
SafehouseAllowTrepass=true
SafehouseAllowFire=true
SafehouseAllowLoot=true
SafehouseAllowRespawn=false
SafehouseDaySurvivedToClaim=0
SafeHouseRemovalTime=144

AllowDestructionBySledgehammer=true
SledgehammerOnlyInSafehouse=false

Faction=true
FactionDaySurvivedToCreate=0
FactionPlayersRequiredForTag=1

AllowCoop=true
SleepAllowed=false
SleepNeeded=false

VoiceEnable=true
VoiceMinDistance=10.0
VoiceMaxDistance=100.0
Voice3D=true

SpeedLimit=70.0
ServerPlayerID=1606282572

MapRemotePlayerVisibility=1
BackupsCount=5
BackupsOnStart=true
BackupsOnVersionChange=true